name: Run Web Tests
run-name: On push - Web Tests Ruan
on:
  push:
  pull_request:
  issues:
  schedule:
    - cron: '0 0 * * *' # Executa todos os dias à meia-noite UTC

jobs:
  web-tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Node.js
        uses: actions/setup-node@v2

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
          sudo npm install @playwright/test@latest
          sudo npx playwright install-deps@latest
          rfbrowser init

      - name: Run RF Web Tests
        run: |
          robot -d ./results -v HEADLESS:true \
          -v BROWSER:chromium tests